name: API Test Automation
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: 'maven'


    - name: Run API Tests
      run: mvn clean test -Dsuite=suite -X

    - name: Upload test resullt
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name:  test-result
        path:
          test-output/reports/
          target/surefire-reports/
          logs/

    - name: Publish Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: TestNG Results
        path: target/surefire-reports/junitreports/TEST-*.xml
        reporter: java-junit
        

          
      
    
    
  
